# This script mirrors CaseLaw's search
# The script asks for SEARCH_TERM and NEED_FULL_TEXT
#
#
# this token is generated by CaseLaw
# it is currently tied to Karen's CaseLaw account
TOKEN=f643c4cfb329a249febbecca90efa2736acf39ce

echo "ENTER SEARCH TERM:"
read SEARCH_TERM
#echo "SEARCH_TERM $SEARCH_TERM"

echo ""

echo "Need Full Text? (y/n)"
read NEED_FULL_TEXT
#echo "NEED_FULL_TEXT $NEED_FULL_TEXT"

getFullText=false
if [[ $NEED_FULL_TEXT == "y" ]]; then
    getFullText=true
else
    getFullText=false
fi

echo ""
#echo "getFullText $getFullText"


curl -# \
-H "Authorization: token $TOKEN" \
"https://api.case.law/v1/cases/?"\
"page_size=10"\
"&search=$SEARCH_TERM"\
"&full_case=$getFullText"\
"&jurisdiction=cal"


#&body_format=text
#&full_case=true

#GET /v1/cases/?page_size=10&search=car+accident&ordering=relevance

#"https://api.case.law/v1/cases/?page_size=10&search=car+accident&full_case=true&jurisdiction=cal&body_format=text"

#"https://api.case.law/v1/cases/?page_size=10&search=car+accident&ordering=relevance"
#"search=$SEARCH_TERM" \


#RESPONSE= ^

#CASE_ID = RESPONSE.results[i].id
#"https://api.case.law/v1/cases/CASE_ID/?full_case=true"



#https://api.case.law/v1/?search=$SEARCH_TERM

#/cases/435800/?full_case=true"


#curl -H \
#"Authorization: token $TOKEN" \
#"https://api.case.law/v1/cases/435800/?full_case=true"

#
#curl "https://api.case.law/v1/cases/?jurisdiction=ill&page_size=1"

#{
#  "count": 183149,
#  "next": "https://api.case.law/v1/cases/?cursor=cD0xODMyLTEyLTAx",
#  "previous": "https://api.case.law/v1/cases/?cursor=bz0xMCZyPTEmcD0xODI4LTEyLTAx"
#  ...
#}
#


#https://case.law/docs/user_pathways/researchers#bulk-downloads
